### ISSUE TITLE
error when importing libamy

### ISSUE THREAD

**Issue by kasparsj** [bwhitman/alles#16]
Hi...
after running:
`sudo python3 setup.py  install`
and following the "Using amy.py's local mode" I'm getting this error:
```
>>> import amy, alles
Using 192.168.1.141 as local IP for multicast IF
>>> amy.live() # starts an audio callback thread to play audio in real time
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kasparsj/Work/alles/amy.py", line 148, in live
    import libamy
ImportError: /usr/local/lib/python3.6/dist-packages/libamy.cpython-36m-x86_64-linux-gnu.so: undefined symbol: raw_file
```

**Comment by bwhitman** [comment]
Ah, apologies. Alles/AMY is fast moving and we re-factored the "live" bit. Instead of rendering audio in Python interpreter, start a desktop alles instance instead, which will play the audio via multicast to Python. See `getting-started.md`. I'll fix up this documentation asap.

**Comment by bwhitman** [comment]
Fixed up the READMEs and etc to reflect this new reality. Thanks for the report

**Comment by kasparsj** [comment]
Thanks man :))
