### ISSUE TITLE
eq no longer working

### ISSUE THREAD

**Issue by drepetto** [bwhitman/alles#20]
import alles
>>> alles.eq_test()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/douglas/Downloads/alles-main/alles.py", line 208, in eq_test
    eset()
NameError: name 'eset' is not defined

**Comment by bwhitman** [comment]
fixed in 4dea5d3

**Comment by drepetto** [comment]
Not sure what's happening, but now this runs, but just makes occasional clicking noises while printing:
>>> alles.reset()
>>> alles.eq_test()
eq_l = 0dB eq_m = 0dB eq_h = 0dB
eq_l = 15dB eq_m = 0dB eq_h = 0dB
eq_l = 0dB eq_m = 0dB eq_h = 15dB
eq_l = 0dB eq_m = 15dB eq_h = 0dB
eq_l = -15dB eq_m = -15dB eq_h = 15dB

**Comment by bwhitman** [comment]
Yeah, we have a regression on eq . investigating...

**Comment by bwhitman** [comment]
dang, dumb error. fixed in firmware, you'll have to update the speaker if you want it
