### ISSUE TITLE
Release parameter ignored on Note Off

### ISSUE THREAD

**Issue by tkell** [bwhitman/alles#23]
When sending a Note Off to a long note (or maybe any note?), the release is ignored:

`alles.send(osc=0, bp0="20000,10,5000,0", bp0_target=alles.TARGET_AMP, wave=alles.SINE,vel=0.1, note=60)`

*wait a few seconds

`alles.send(osc=0, vel=0)`

The note is cut off quickly, rather than playing with a 5000ms release.

**Comment by bwhitman** [comment]
thanks for the report! I'm not seeing this on my setup, actually. For me, the note slowly ramps down in volume over 5s. It's most likely your speakers were flashed before I fixed a related bug. 
If you are able, try to either [run the latest software version of Alles](https://github.com/bwhitman/alles/blob/main/getting-started.md#alles-on-your-computer) and see if it still happens, or, [upgrade the firmware to the latest over USB.](https://github.com/bwhitman/alles/blob/main/alles-flashing.md) (Your speakers will not flash remotely until you flash them over USB, I can also do yours in person if it's easier.)

**Comment by tkell** [comment]
Got it, I will try these things, hopefully this week!

**Comment by tkell** [comment]
Hmm, I am working through the upgrade firmware steps, and I don't have `idf.py` in the alles repo?  I just pulled latest, and am at 582cdd9.

**Comment by bwhitman** [comment]
`idf.py` gets added to your path when you run `. ~/esp/esp-idf/export.sh`

**Comment by tkell** [comment]
ahhh, I was doing it in another Terminal window, got it!

**Comment by bwhitman** [comment]
Yes! I will update the docs with that

**Comment by tkell** [comment]
Fixed, ty ty!

**Comment by bwhitman** [comment]
Awesome !! Thanks for the report
