### ISSUE TITLE
Alles no longer builds on recent ESP-IDF versions

### ISSUE THREAD

**Issue by vaeinoe** [bwhitman/alles#47]
I flashed three NodeMCUs with the Alles firmware. The instructions for flashing Alles at https://github.com/bwhitman/alles/blob/main/alles-flashing.md mention "You should first install ESP-IDF on your system if you haven't already. We tend to use the master branch of the IDF as we use some newer features."

It seems the latest master and 5.x in general no longer work with the current version of Alles code, based on the amount of compile errors I got when following the instructions. After checking out 4.4 and updating submodules, flashing was successful.

Perhaps the documentation should be updated to reflect that one should specifically install ESP-IDF 4.4 - or the codebase updated to support 5.x? I'm not sure which one is the desired short term fix, so made an issue instead of a PR suggestion.

**Comment by bwhitman** [comment]
Yes, good catch. That "we build on master" was once true, but things changed quite a bit at 5.0. I think I can get it back compiling on a 5.x release, but for now, I'll change the building / flashing README to clone 4.4, which as you figured out, is a stable version that works great with Alles.

**Comment by bwhitman** [comment]
ok, did that! The issue with 5.x branches is that some of the multicast stuff we use moved to an external component. I'll make a new issue to tackle that later, but 4.4 is solid and works fine for us now. thank you !
