### ISSUE TITLE
WiFi authentication page doesn't work on recent Android

### ISSUE THREAD

**Issue by cibomahto** [bwhitman/alles#56]
Using a freshly built Alles image, I get the message "Header fields are too long for server to interpret" after connecting to the WiFi from my Android phone:

![2023-06-20 13 52 35](https://github.com/bwhitman/alles/assets/44493/7742563b-680e-4c4f-97cc-fc49c34a7f9f)

Steps to reproduce:
1. Build Alles binary (using Docker image to ensure clean environment)
2. Load binary onto Alles, reboot
3. On phone, connect to the new wifi network
4. Wait until the 'sign into wifi network' prompt appears, then accept it
5. The phone shows the above page

If I manually configure the phone to use the wifi network without a connection, then open http://10.10.0.1 in a browser, the configuration page is able to load.

I think the solution is simple- CONFIG_HTTPD_MAX_REQ_HDR_LEN needs to be increased:
https://github.com/bwhitman/alles/blob/main/sdkconfig#L375

For instance to 1024:
https://esp32.com/viewtopic.php?t=28702

**Comment by bwhitman** [comment]
Thanks matt! I haven't run into this so can't confirm it's a fix, but i did confirm it doesn't break my existing setup, so i've added it.
